"""init

Revision ID: 16cd53acb59d
Revises: 
Create Date: 2025-08-08 22:50:59.337088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '16cd53acb59d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('auth_permission_content_type_id_codename_01ab375a_uniq'), table_name='auth_permission')
    op.drop_table('auth_permission')
    op.drop_table('django_admin_log')
    op.drop_table('django_migrations')
    op.drop_index(op.f('user_id'), table_name='climber')
    op.drop_table('climber')
    op.drop_index(op.f('django_content_type_app_label_model_76bd3d3b_uniq'), table_name='django_content_type')
    op.drop_table('django_content_type')
    op.drop_index(op.f('username'), table_name='auth_user')
    op.drop_table('auth_user')
    op.drop_table('editor_role')
    op.drop_index(op.f('django_session_expire_date_a5c62663'), table_name='django_session')
    op.drop_table('django_session')
    op.drop_index(op.f('auth_user_user_permissions_user_id_permission_id_14a6b632_uniq'), table_name='auth_user_user_permissions')
    op.drop_table('auth_user_user_permissions')
    op.drop_index(op.f('auth_user_groups_user_id_group_id_94350c0c_uniq'), table_name='auth_user_groups')
    op.drop_table('auth_user_groups')
    op.drop_index(op.f('auth_group_permissions_group_id_permission_id_0cd325b0_uniq'), table_name='auth_group_permissions')
    op.drop_table('auth_group_permissions')
    op.drop_index(op.f('hashkey'), table_name='captcha_captchastore')
    op.drop_table('captcha_captchastore')
    op.drop_table('peak_comment')
    op.drop_index(op.f('name'), table_name='auth_group')
    op.drop_table('auth_group')
    op.alter_column('api_user', 'username',
               existing_type=mysql.VARCHAR(length=150),
               type_=sqlmodel.sql.sqltypes.AutoString(length=128),
               existing_nullable=False)
    op.alter_column('api_user', 'email',
               existing_type=mysql.VARCHAR(length=254),
               type_=sqlmodel.sql.sqltypes.AutoString(length=255),
               existing_nullable=False)
    op.alter_column('api_user', 'first_name',
               existing_type=mysql.VARCHAR(length=150),
               type_=sqlmodel.sql.sqltypes.AutoString(length=128),
               nullable=False)
    op.alter_column('api_user', 'last_name',
               existing_type=mysql.VARCHAR(length=150),
               type_=sqlmodel.sql.sqltypes.AutoString(length=128),
               nullable=False)
    op.alter_column('api_user', 'middle_name',
               existing_type=mysql.VARCHAR(length=150),
               type_=sqlmodel.sql.sqltypes.AutoString(length=128),
               nullable=False)
    op.alter_column('api_user', 'is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('api_user', 'is_editor',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.drop_index(op.f('email'), table_name='api_user')
    op.drop_index(op.f('username'), table_name='api_user')
    op.create_index(op.f('ix_api_user_email'), 'api_user', ['email'], unique=True)
    op.create_index(op.f('ix_api_user_username'), 'api_user', ['username'], unique=True)
    op.alter_column('geo_city', 'id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('geo_city', 'alternatenames',
               existing_type=mysql.VARCHAR(length=4000),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('geo_city', 'latitude',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('geo_city', 'longitude',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_index(op.f('geo_city_admin1_324eb546'), table_name='geo_city')
    op.drop_index(op.f('geo_city_country_0ecae09d'), table_name='geo_city')
    op.create_index(op.f('ix_geo_city_admin1'), 'geo_city', ['admin1'], unique=False)
    op.create_index(op.f('ix_geo_city_cc2'), 'geo_city', ['cc2'], unique=False)
    op.create_index(op.f('ix_geo_city_country'), 'geo_city', ['country'], unique=False)
    op.create_index(op.f('ix_geo_city_geonameid'), 'geo_city', ['geonameid'], unique=False)
    op.alter_column('geo_country', 'id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('geo_country_currency_code_b9e45564'), table_name='geo_country')
    op.drop_index(op.f('geo_country_geoname_id_c6e268f9'), table_name='geo_country')
    op.drop_index(op.f('geo_country_iso3_6f932512'), table_name='geo_country')
    op.drop_index(op.f('geo_country_iso_94990b30'), table_name='geo_country')
    op.drop_index(op.f('geo_country_iso_num_6f0d4218'), table_name='geo_country')
    op.create_index(op.f('ix_geo_country_currency_code'), 'geo_country', ['currency_code'], unique=False)
    op.create_index(op.f('ix_geo_country_currency_name'), 'geo_country', ['currency_name'], unique=False)
    op.create_index(op.f('ix_geo_country_geoname_id'), 'geo_country', ['geoname_id'], unique=False)
    op.create_index(op.f('ix_geo_country_iso'), 'geo_country', ['iso'], unique=False)
    op.create_index(op.f('ix_geo_country_iso3'), 'geo_country', ['iso3'], unique=False)
    op.create_index(op.f('ix_geo_country_iso_num'), 'geo_country', ['iso_num'], unique=False)
    op.alter_column('geo_country_language', 'id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('geo_country_language_country_iso3_028226dd'), table_name='geo_country_language')
    op.drop_index(op.f('geo_country_language_lang_code_bd4d623f'), table_name='geo_country_language')
    op.create_index(op.f('ix_geo_country_language_country_iso3'), 'geo_country_language', ['country_iso3'], unique=False)
    op.create_index(op.f('ix_geo_country_language_lang_code'), 'geo_country_language', ['lang_code'], unique=False)
    op.alter_column('geo_country_neighbour', 'id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('geo_country_neighbour_country_iso3_48ac1179'), table_name='geo_country_neighbour')
    op.drop_index(op.f('geo_country_neighbour_neighbour_iso_1b12369c'), table_name='geo_country_neighbour')
    op.create_index(op.f('ix_geo_country_neighbour_country_iso3'), 'geo_country_neighbour', ['country_iso3'], unique=False)
    op.create_index(op.f('ix_geo_country_neighbour_neighbour_iso'), 'geo_country_neighbour', ['neighbour_iso'], unique=False)
    op.alter_column('geo_country_subject', 'id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('geo_country_subject_code_379c7b24'), table_name='geo_country_subject')
    op.drop_index(op.f('geo_country_subject_country_iso_8f12fc81'), table_name='geo_country_subject')
    op.drop_index(op.f('geo_country_subject_geoname_id_4b120fad'), table_name='geo_country_subject')
    op.create_index(op.f('ix_geo_country_subject_code'), 'geo_country_subject', ['code'], unique=False)
    op.create_index(op.f('ix_geo_country_subject_country_iso'), 'geo_country_subject', ['country_iso'], unique=False)
    op.create_index(op.f('ix_geo_country_subject_geoname_id'), 'geo_country_subject', ['geoname_id'], unique=False)
    op.alter_column('geo_russia_subject', 'id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_geo_russia_subject_code'), 'geo_russia_subject', ['code'], unique=False)
    op.create_index(op.f('ix_geo_russia_subject_country_iso'), 'geo_russia_subject', ['country_iso'], unique=False)
    op.create_index(op.f('ix_geo_russia_subject_gai_code'), 'geo_russia_subject', ['gai_code'], unique=False)
    op.create_index(op.f('ix_geo_russia_subject_geoname_id'), 'geo_russia_subject', ['geoname_id'], unique=False)
    op.create_index(op.f('ix_geo_russia_subject_iso_3166_2_code'), 'geo_russia_subject', ['iso_3166_2_code'], unique=False)
    op.add_column('geo_ukraine_subject', sa.Column('iso_3166_2_code', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False))
    op.alter_column('geo_ukraine_subject', 'id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_geo_ukraine_subject_code'), 'geo_ukraine_subject', ['code'], unique=False)
    op.create_index(op.f('ix_geo_ukraine_subject_country_iso'), 'geo_ukraine_subject', ['country_iso'], unique=False)
    op.create_index(op.f('ix_geo_ukraine_subject_geoname_id'), 'geo_ukraine_subject', ['geoname_id'], unique=False)
    op.create_index(op.f('ix_geo_ukraine_subject_iso_3166_2_code'), 'geo_ukraine_subject', ['iso_3166_2_code'], unique=False)
    op.alter_column('geopoint', 'id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('geopoint', 'latitude',
               existing_type=mysql.DECIMAL(precision=10, scale=6),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('geopoint', 'longitude',
               existing_type=mysql.DECIMAL(precision=10, scale=6),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('peak', 'id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('peak', 'slug',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.alter_column('peak', 'ridge_id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               nullable=True)
    op.alter_column('peak', 'name',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('peak', 'description',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('peak', 'point_id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('peak', 'photo',
               existing_type=mysql.VARCHAR(length=100),
               type_=sqlmodel.sql.sqltypes.AutoString(length=128),
               existing_nullable=True)
    op.drop_index(op.f('peak_changed_ef1ae660'), table_name='peak')
    op.create_unique_constraint(None, 'peak', ['photo'])
    op.drop_constraint(op.f('peak_editor_id_e8ca26c8_fk_auth_user_id'), 'peak', type_='foreignkey')
    op.create_foreign_key(None, 'peak', 'api_user', ['editor_id'], ['id'])
    op.alter_column('peak_photo', 'id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('peak_photo', 'peak_id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               nullable=True)
    op.alter_column('peak_photo', 'photo',
               existing_type=mysql.VARCHAR(length=100),
               type_=sqlmodel.sql.sqltypes.AutoString(length=128),
               existing_nullable=True)
    op.create_unique_constraint(None, 'peak_photo', ['photo'])
    op.alter_column('ridge', 'id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('ridge', 'slug',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('ridge', 'description',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ridge_changed_4fd26b27'), table_name='ridge')
    op.drop_constraint(op.f('ridge_editor_id_bddf00aa_fk_auth_user_id'), 'ridge', type_='foreignkey')
    op.create_foreign_key(None, 'ridge', 'api_user', ['editor_id'], ['id'])
    op.alter_column('ridge_info_link', 'id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('ridge_info_link', 'ridge_id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               nullable=True)
    op.alter_column('ridge_info_link', 'link',
               existing_type=mysql.VARCHAR(length=128),
               type_=app.models.mountains.HttpUrlType(length=2083),
               existing_nullable=False)
    op.create_index(op.f('ix_ridge_info_link_link'), 'ridge_info_link', ['link'], unique=True)
    op.alter_column('route', 'id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('route', 'peak_id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               nullable=True)
    op.alter_column('route', 'name',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('route', 'description',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('route', 'short_description',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('route', 'recommended_equipment',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('route', 'photo',
               existing_type=mysql.VARCHAR(length=100),
               type_=sqlmodel.sql.sqltypes.AutoString(length=128),
               existing_nullable=True)
    op.alter_column('route', 'map_image',
               existing_type=mysql.VARCHAR(length=100),
               type_=sqlmodel.sql.sqltypes.AutoString(length=128),
               existing_nullable=True)
    op.alter_column('route', 'descent',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('route_changed_00f40d6e'), table_name='route')
    op.create_unique_constraint(None, 'route', ['photo'])
    op.create_unique_constraint(None, 'route', ['map_image'])
    op.drop_constraint(op.f('route_editor_id_9e1c99c3_fk_auth_user_id'), 'route', type_='foreignkey')
    op.create_foreign_key(None, 'route', 'api_user', ['editor_id'], ['id'])
    op.drop_column('route', 'number')
    op.alter_column('route_photo', 'id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('route_photo', 'route_id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               nullable=True)
    op.alter_column('route_photo', 'photo',
               existing_type=mysql.VARCHAR(length=100),
               type_=sqlmodel.sql.sqltypes.AutoString(length=128),
               existing_nullable=True)
    op.create_unique_constraint(None, 'route_photo', ['photo'])
    op.alter_column('route_point', 'id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('route_point', 'route_id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               nullable=True)
    op.alter_column('route_point', 'point_id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('route_section', 'id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('route_section', 'route_id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               nullable=True)
    op.alter_column('route_section', 'description',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('route_section', 'description',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.alter_column('route_section', 'route_id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               nullable=False)
    op.alter_column('route_section', 'id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('route_point', 'point_id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=True)
    op.alter_column('route_point', 'route_id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               nullable=False)
    op.alter_column('route_point', 'id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'route_photo', type_='unique')
    op.alter_column('route_photo', 'photo',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=128),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('route_photo', 'route_id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               nullable=False)
    op.alter_column('route_photo', 'id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('route', sa.Column('number', mysql.SMALLINT(unsigned=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'route', type_='foreignkey')
    op.create_foreign_key(op.f('route_editor_id_9e1c99c3_fk_auth_user_id'), 'route', 'auth_user', ['editor_id'], ['id'])
    op.drop_constraint(None, 'route', type_='unique')
    op.drop_constraint(None, 'route', type_='unique')
    op.create_index(op.f('route_changed_00f40d6e'), 'route', ['changed'], unique=False)
    op.alter_column('route', 'descent',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.alter_column('route', 'map_image',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=128),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('route', 'photo',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=128),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('route', 'recommended_equipment',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.alter_column('route', 'short_description',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.alter_column('route', 'description',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.alter_column('route', 'name',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.alter_column('route', 'peak_id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               nullable=False)
    op.alter_column('route', 'id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_ridge_info_link_link'), table_name='ridge_info_link')
    op.alter_column('ridge_info_link', 'link',
               existing_type=app.models.mountains.HttpUrlType(length=2083),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=False)
    op.alter_column('ridge_info_link', 'ridge_id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               nullable=False)
    op.alter_column('ridge_info_link', 'id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'ridge', type_='foreignkey')
    op.create_foreign_key(op.f('ridge_editor_id_bddf00aa_fk_auth_user_id'), 'ridge', 'auth_user', ['editor_id'], ['id'])
    op.create_index(op.f('ridge_changed_4fd26b27'), 'ridge', ['changed'], unique=False)
    op.alter_column('ridge', 'description',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.alter_column('ridge', 'slug',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('ridge', 'id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'peak_photo', type_='unique')
    op.alter_column('peak_photo', 'photo',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=128),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('peak_photo', 'peak_id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               nullable=False)
    op.alter_column('peak_photo', 'id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'peak', type_='foreignkey')
    op.create_foreign_key(op.f('peak_editor_id_e8ca26c8_fk_auth_user_id'), 'peak', 'auth_user', ['editor_id'], ['id'])
    op.drop_constraint(None, 'peak', type_='unique')
    op.create_index(op.f('peak_changed_ef1ae660'), 'peak', ['changed'], unique=False)
    op.alter_column('peak', 'photo',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=128),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('peak', 'point_id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=True)
    op.alter_column('peak', 'description',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.alter_column('peak', 'name',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.alter_column('peak', 'ridge_id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               nullable=False)
    op.alter_column('peak', 'slug',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('peak', 'id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('geopoint', 'longitude',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=10, scale=6),
               existing_nullable=False)
    op.alter_column('geopoint', 'latitude',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=10, scale=6),
               existing_nullable=False)
    op.alter_column('geopoint', 'id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_geo_ukraine_subject_iso_3166_2_code'), table_name='geo_ukraine_subject')
    op.drop_index(op.f('ix_geo_ukraine_subject_geoname_id'), table_name='geo_ukraine_subject')
    op.drop_index(op.f('ix_geo_ukraine_subject_country_iso'), table_name='geo_ukraine_subject')
    op.drop_index(op.f('ix_geo_ukraine_subject_code'), table_name='geo_ukraine_subject')
    op.alter_column('geo_ukraine_subject', 'id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('geo_ukraine_subject', 'iso_3166_2_code')
    op.drop_index(op.f('ix_geo_russia_subject_iso_3166_2_code'), table_name='geo_russia_subject')
    op.drop_index(op.f('ix_geo_russia_subject_geoname_id'), table_name='geo_russia_subject')
    op.drop_index(op.f('ix_geo_russia_subject_gai_code'), table_name='geo_russia_subject')
    op.drop_index(op.f('ix_geo_russia_subject_country_iso'), table_name='geo_russia_subject')
    op.drop_index(op.f('ix_geo_russia_subject_code'), table_name='geo_russia_subject')
    op.alter_column('geo_russia_subject', 'id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_geo_country_subject_geoname_id'), table_name='geo_country_subject')
    op.drop_index(op.f('ix_geo_country_subject_country_iso'), table_name='geo_country_subject')
    op.drop_index(op.f('ix_geo_country_subject_code'), table_name='geo_country_subject')
    op.create_index(op.f('geo_country_subject_geoname_id_4b120fad'), 'geo_country_subject', ['geoname_id'], unique=False)
    op.create_index(op.f('geo_country_subject_country_iso_8f12fc81'), 'geo_country_subject', ['country_iso'], unique=False)
    op.create_index(op.f('geo_country_subject_code_379c7b24'), 'geo_country_subject', ['code'], unique=False)
    op.alter_column('geo_country_subject', 'id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_geo_country_neighbour_neighbour_iso'), table_name='geo_country_neighbour')
    op.drop_index(op.f('ix_geo_country_neighbour_country_iso3'), table_name='geo_country_neighbour')
    op.create_index(op.f('geo_country_neighbour_neighbour_iso_1b12369c'), 'geo_country_neighbour', ['neighbour_iso'], unique=False)
    op.create_index(op.f('geo_country_neighbour_country_iso3_48ac1179'), 'geo_country_neighbour', ['country_iso3'], unique=False)
    op.alter_column('geo_country_neighbour', 'id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_geo_country_language_lang_code'), table_name='geo_country_language')
    op.drop_index(op.f('ix_geo_country_language_country_iso3'), table_name='geo_country_language')
    op.create_index(op.f('geo_country_language_lang_code_bd4d623f'), 'geo_country_language', ['lang_code'], unique=False)
    op.create_index(op.f('geo_country_language_country_iso3_028226dd'), 'geo_country_language', ['country_iso3'], unique=False)
    op.alter_column('geo_country_language', 'id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_geo_country_iso_num'), table_name='geo_country')
    op.drop_index(op.f('ix_geo_country_iso3'), table_name='geo_country')
    op.drop_index(op.f('ix_geo_country_iso'), table_name='geo_country')
    op.drop_index(op.f('ix_geo_country_geoname_id'), table_name='geo_country')
    op.drop_index(op.f('ix_geo_country_currency_name'), table_name='geo_country')
    op.drop_index(op.f('ix_geo_country_currency_code'), table_name='geo_country')
    op.create_index(op.f('geo_country_iso_num_6f0d4218'), 'geo_country', ['iso_num'], unique=False)
    op.create_index(op.f('geo_country_iso_94990b30'), 'geo_country', ['iso'], unique=False)
    op.create_index(op.f('geo_country_iso3_6f932512'), 'geo_country', ['iso3'], unique=False)
    op.create_index(op.f('geo_country_geoname_id_c6e268f9'), 'geo_country', ['geoname_id'], unique=False)
    op.create_index(op.f('geo_country_currency_code_b9e45564'), 'geo_country', ['currency_code'], unique=False)
    op.alter_column('geo_country', 'id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_geo_city_geonameid'), table_name='geo_city')
    op.drop_index(op.f('ix_geo_city_country'), table_name='geo_city')
    op.drop_index(op.f('ix_geo_city_cc2'), table_name='geo_city')
    op.drop_index(op.f('ix_geo_city_admin1'), table_name='geo_city')
    op.create_index(op.f('geo_city_country_0ecae09d'), 'geo_city', ['country'], unique=False)
    op.create_index(op.f('geo_city_admin1_324eb546'), 'geo_city', ['admin1'], unique=False)
    op.alter_column('geo_city', 'longitude',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
    op.alter_column('geo_city', 'latitude',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
    op.alter_column('geo_city', 'alternatenames',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.VARCHAR(length=4000),
               existing_nullable=True)
    op.alter_column('geo_city', 'id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_api_user_username'), table_name='api_user')
    op.drop_index(op.f('ix_api_user_email'), table_name='api_user')
    op.create_index(op.f('username'), 'api_user', ['username'], unique=True)
    op.create_index(op.f('email'), 'api_user', ['email'], unique=True)
    op.alter_column('api_user', 'is_editor',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('api_user', 'is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('api_user', 'middle_name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=128),
               type_=mysql.VARCHAR(length=150),
               nullable=True)
    op.alter_column('api_user', 'last_name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=128),
               type_=mysql.VARCHAR(length=150),
               nullable=True)
    op.alter_column('api_user', 'first_name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=128),
               type_=mysql.VARCHAR(length=150),
               nullable=True)
    op.alter_column('api_user', 'email',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=255),
               type_=mysql.VARCHAR(length=254),
               existing_nullable=False)
    op.alter_column('api_user', 'username',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=128),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=False)
    op.create_table('auth_group',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('name'), 'auth_group', ['name'], unique=True)
    op.create_table('peak_comment',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('nickname', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=254), nullable=True),
    sa.Column('body', mysql.LONGTEXT(), nullable=False),
    sa.Column('created_on', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('author_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('peak_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('photo', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('parent_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('city', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('country', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('country_code', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('ip_address', mysql.CHAR(length=39), nullable=True),
    sa.Column('region', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('homepage', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('doc', mysql.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['auth_user.id'], name=op.f('mountains_peakcomment_author_id_aaece1c8_fk_auth_user_id')),
    sa.ForeignKeyConstraint(['parent_id'], ['peak_comment.id'], name=op.f('peak_comment_parent_id_2ac1ba79_fk_peak_comment_id')),
    sa.ForeignKeyConstraint(['peak_id'], ['peak.id'], name=op.f('mountains_peakcomment_peak_id_7d8a7d88_fk_peak_id')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('captcha_captchastore',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('challenge', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('response', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('hashkey', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('expiration', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('hashkey'), 'captcha_captchastore', ['hashkey'], unique=True)
    op.create_table('auth_group_permissions',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('group_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name=op.f('auth_group_permissions_group_id_b120cbf9_fk_auth_group_id')),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name=op.f('auth_group_permissio_permission_id_84c5c92e_fk_auth_perm')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('auth_group_permissions_group_id_permission_id_0cd325b0_uniq'), 'auth_group_permissions', ['group_id', 'permission_id'], unique=True)
    op.create_table('auth_user_groups',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name=op.f('auth_user_groups_group_id_97559544_fk_auth_group_id')),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name=op.f('auth_user_groups_user_id_6a12ed8b_fk_auth_user_id')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('auth_user_groups_user_id_group_id_94350c0c_uniq'), 'auth_user_groups', ['user_id', 'group_id'], unique=True)
    op.create_table('auth_user_user_permissions',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name=op.f('auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm')),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name=op.f('auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('auth_user_user_permissions_user_id_permission_id_14a6b632_uniq'), 'auth_user_user_permissions', ['user_id', 'permission_id'], unique=True)
    op.create_table('django_session',
    sa.Column('session_key', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('session_data', mysql.LONGTEXT(), nullable=False),
    sa.Column('expire_date', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('session_key'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('django_session_expire_date_a5c62663'), 'django_session', ['expire_date'], unique=False)
    op.create_table('editor_role',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('climber_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['climber_id'], ['climber.id'], name=op.f('editor_role_climber_id_32564c04_fk_climber_id')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('auth_user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('password', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('last_login', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('is_superuser', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=254), nullable=False),
    sa.Column('is_staff', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('date_joined', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('username'), 'auth_user', ['username'], unique=True)
    op.create_table('django_content_type',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('app_label', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('model', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('django_content_type_app_label_model_76bd3d3b_uniq'), 'django_content_type', ['app_label', 'model'], unique=True)
    op.create_table('climber',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('middle_name', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('geocity_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['geocity_id'], ['geo_city.id'], name=op.f('climber_geocity_id_d7ada166_fk_geo_city_id')),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name=op.f('climber_user_id_eac9678c_fk_auth_user_id')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('user_id'), 'climber', ['user_id'], unique=True)
    op.create_table('django_migrations',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('app', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('applied', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('django_admin_log',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('action_time', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('object_id', mysql.LONGTEXT(), nullable=True),
    sa.Column('object_repr', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('action_flag', mysql.SMALLINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('change_message', mysql.LONGTEXT(), nullable=False),
    sa.Column('content_type_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint('(`action_flag` >= 0)', name=op.f('django_admin_log_chk_1')),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name=op.f('django_admin_log_content_type_id_c4bce8eb_fk_django_co')),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name=op.f('django_admin_log_user_id_c564eba6_fk_auth_user_id')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('auth_permission',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('content_type_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('codename', mysql.VARCHAR(length=100), nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name=op.f('auth_permission_content_type_id_2f476e4b_fk_django_co')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('auth_permission_content_type_id_codename_01ab375a_uniq'), 'auth_permission', ['content_type_id', 'codename'], unique=True)
    # ### end Alembic commands ###
